"""
Django settings for Email_schedule_cron_django_celery_proj project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from decouple import config
import decouple
from celery.schedules import crontab


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mgn311ra01$$i1*eopz!!6vu_f^njbtaav9evwda7dbshh&q+h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'django_celery_beat',
    'Email_schedule_cron_django_celery_app.apps.EmailScheduleCronDjangoCeleryAppConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Email_schedule_cron_django_celery_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Email_schedule_cron_django_celery_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


########################################################################

# EMAIL SETTINGS CONFIG


EMAIL_BACKEND=decouple.config('EMAIL_BACKEND')

EMAIL_HOST=decouple.config('EMAIL_HOST')

EMAIL_PORT=587

EMAIL_USE_TLS=True

EMAIL_HOST_USER=decouple.config('EMAIL_HOST_USER')

EMAIL_HOST_PASSWORD=decouple.config('EMAIL_HOST_PASSWORD')

DEFAULT_EMAIL_FROM = "djangocelery60@gmail.com"

################################################################

#CELERY SETTINGS CONFIG

CELERY_BROKER_URL= "amqps://bitbdcvn:cmtCe3URq_S8uFslJQNi-WJgvR3rbI0F@baboon.rmq.cloudamqp.com/bitbdcvn"

CELERY_ACCEPT_CONTENT= ["application/json",]

CELERY_TASK_SERIALIZER="json"

CELERY_RESULT_SERIALIZER="json"

CELERY_RESULT_BACKEND= "django-db"

################################################################

#CELERY_BEAT_SETTINGS

CELERY_BEAT_SCHEDULE={
    "schedule_task":{
        "task":"Email_schedule_cron_django_celery_app.tasks.add",
        "schedule":10.0,
        "args":(10,20),
    }
}


